src/hawkbit-client: define _XOPEN_SOURCE for using strptime
Using strptime() requires _XOPEN_SOURCE to be set.
Otherwise, compilation will warn:

| src/hawkbit-client.c:392:17: warning: implicit declaration of function ‘strptime’; did you mean ‘strftime’? [-Wimplicit-function-declaration]
|                  strptime(sleeptime_str, "%T", &time);
|                  ^~~~~~~~
|                  strftime

Signed-off-by: Enrico Joerns <ejo@pengutronix.de>